services:
  web:
    image: harihk27/student-feedback-devops:latest
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - feedback_data:/data
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 3

volumes:
  feedback_data:
